# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='desctiption',
            new_name='description',
        ),
    ]
