# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_author', to='client.Client')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_paricipant', to='client.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
